name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, ready_for_review]
  issue_comment:

jobs:
  add-owner:
    runs-on: ubuntu-latest
    steps:
      - uses: anuraaga/subowners@v0.0.1
